/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppListasIndexRouteImport } from './routes/app/listas/index'
import { Route as AppJogosIndexRouteImport } from './routes/app/jogos/index'
import { Route as AppDiarioIndexRouteImport } from './routes/app/diario/index'
import { Route as AuthLoginIndexRouteImport } from './routes/_auth/login/index'
import { Route as AuthCadastroIndexRouteImport } from './routes/_auth/cadastro/index'
import { Route as AppPerfilUserIdIndexRouteImport } from './routes/app/perfil/$userId/index'
import { Route as AppListasListaIdIndexRouteImport } from './routes/app/listas/$listaId/index'
import { Route as AppJogosJogoIdIndexRouteImport } from './routes/app/jogos/$jogoId/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppListasIndexRoute = AppListasIndexRouteImport.update({
  id: '/listas/',
  path: '/listas/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJogosIndexRoute = AppJogosIndexRouteImport.update({
  id: '/jogos/',
  path: '/jogos/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDiarioIndexRoute = AppDiarioIndexRouteImport.update({
  id: '/diario/',
  path: '/diario/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/_auth/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCadastroIndexRoute = AuthCadastroIndexRouteImport.update({
  id: '/_auth/cadastro/',
  path: '/cadastro/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPerfilUserIdIndexRoute = AppPerfilUserIdIndexRouteImport.update({
  id: '/perfil/$userId/',
  path: '/perfil/$userId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppListasListaIdIndexRoute = AppListasListaIdIndexRouteImport.update({
  id: '/listas/$listaId/',
  path: '/listas/$listaId/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppJogosJogoIdIndexRoute = AppJogosJogoIdIndexRouteImport.update({
  id: '/jogos/$jogoId/',
  path: '/jogos/$jogoId/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/cadastro': typeof AuthCadastroIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/app/diario': typeof AppDiarioIndexRoute
  '/app/jogos': typeof AppJogosIndexRoute
  '/app/listas': typeof AppListasIndexRoute
  '/app/jogos/$jogoId': typeof AppJogosJogoIdIndexRoute
  '/app/listas/$listaId': typeof AppListasListaIdIndexRoute
  '/app/perfil/$userId': typeof AppPerfilUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/cadastro': typeof AuthCadastroIndexRoute
  '/login': typeof AuthLoginIndexRoute
  '/app/diario': typeof AppDiarioIndexRoute
  '/app/jogos': typeof AppJogosIndexRoute
  '/app/listas': typeof AppListasIndexRoute
  '/app/jogos/$jogoId': typeof AppJogosJogoIdIndexRoute
  '/app/listas/$listaId': typeof AppListasListaIdIndexRoute
  '/app/perfil/$userId': typeof AppPerfilUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/_auth/cadastro/': typeof AuthCadastroIndexRoute
  '/_auth/login/': typeof AuthLoginIndexRoute
  '/app/diario/': typeof AppDiarioIndexRoute
  '/app/jogos/': typeof AppJogosIndexRoute
  '/app/listas/': typeof AppListasIndexRoute
  '/app/jogos/$jogoId/': typeof AppJogosJogoIdIndexRoute
  '/app/listas/$listaId/': typeof AppListasListaIdIndexRoute
  '/app/perfil/$userId/': typeof AppPerfilUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/diario'
    | '/app/jogos'
    | '/app/listas'
    | '/app/jogos/$jogoId'
    | '/app/listas/$listaId'
    | '/app/perfil/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/cadastro'
    | '/login'
    | '/app/diario'
    | '/app/jogos'
    | '/app/listas'
    | '/app/jogos/$jogoId'
    | '/app/listas/$listaId'
    | '/app/perfil/$userId'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/_auth/cadastro/'
    | '/_auth/login/'
    | '/app/diario/'
    | '/app/jogos/'
    | '/app/listas/'
    | '/app/jogos/$jogoId/'
    | '/app/listas/$listaId/'
    | '/app/perfil/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthCadastroIndexRoute: typeof AuthCadastroIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/listas/': {
      id: '/app/listas/'
      path: '/listas'
      fullPath: '/app/listas'
      preLoaderRoute: typeof AppListasIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/jogos/': {
      id: '/app/jogos/'
      path: '/jogos'
      fullPath: '/app/jogos'
      preLoaderRoute: typeof AppJogosIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/diario/': {
      id: '/app/diario/'
      path: '/diario'
      fullPath: '/app/diario'
      preLoaderRoute: typeof AppDiarioIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login/': {
      id: '/_auth/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/cadastro/': {
      id: '/_auth/cadastro/'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof AuthCadastroIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/perfil/$userId/': {
      id: '/app/perfil/$userId/'
      path: '/perfil/$userId'
      fullPath: '/app/perfil/$userId'
      preLoaderRoute: typeof AppPerfilUserIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/listas/$listaId/': {
      id: '/app/listas/$listaId/'
      path: '/listas/$listaId'
      fullPath: '/app/listas/$listaId'
      preLoaderRoute: typeof AppListasListaIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/jogos/$jogoId/': {
      id: '/app/jogos/$jogoId/'
      path: '/jogos/$jogoId'
      fullPath: '/app/jogos/$jogoId'
      preLoaderRoute: typeof AppJogosJogoIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppDiarioIndexRoute: typeof AppDiarioIndexRoute
  AppJogosIndexRoute: typeof AppJogosIndexRoute
  AppListasIndexRoute: typeof AppListasIndexRoute
  AppJogosJogoIdIndexRoute: typeof AppJogosJogoIdIndexRoute
  AppListasListaIdIndexRoute: typeof AppListasListaIdIndexRoute
  AppPerfilUserIdIndexRoute: typeof AppPerfilUserIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppDiarioIndexRoute: AppDiarioIndexRoute,
  AppJogosIndexRoute: AppJogosIndexRoute,
  AppListasIndexRoute: AppListasIndexRoute,
  AppJogosJogoIdIndexRoute: AppJogosJogoIdIndexRoute,
  AppListasListaIdIndexRoute: AppListasListaIdIndexRoute,
  AppPerfilUserIdIndexRoute: AppPerfilUserIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthCadastroIndexRoute: AuthCadastroIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
